### ISSUE TITLE
Manifest Loops

### ISSUE THREAD

**Issue by Nitecon** [configset/cfs#49]
**Is your feature request related to a problem? Please describe.**
We need the ability to make use of manifest loops.  As an example, when trying to deploy a highly available Kafka cluster majority of the files remain exactly the same with just the server names and broker ID's changing in the simplest case.  This would allow us to greatly simplify how CFS is executed to set up an HA environment.

**Describe the solution you'd like**
As a new step provide the capability to run a loop for instance:
```
---
variables:
  BROKER_ID: 1
  HOST: hostname-${BROKER_ID}.example.com
steps:
  - loop: install.yml
    until: BROKER_ID == 3
    inc: BROKER_ID++
```
This would allow for the ability to loop over the current install as a templated cfs install manifest, setting the BROKER_ID template variable in the subsequent manifest to the the increment value (standard arithmetic operator) until that particular value matches the until line.

**Describe alternatives you've considered**
Creating and copying multiple install files with the BROKER_ID variable defined as a new value in each works just fine but it becomes tedious to keep up to date when changing additional capabilities or adding new features to services.

**Additional context**
